Repository jenkins-x-plugins/jx-secret, pull requests merged in 2020-09, with the labels that each got.

#58 fix: lets use the secret data keys in the secret schema
  pkg/cmd/edit/edit.go
  pkg/cmd/populate/populate.go
  pkg/cmd/populate/populate_test.go
  pkg/cmd/populate/templater_test.go
  pkg/cmd/populate/test_data/expected/jenkins-maven-settings/settings.xml/bucketrepo.xml
  pkg/cmd/populate/test_data/expected/jenkins-maven-settings/settings.xml/nexus.xml
  pkg/cmd/populate/test_data/expected/jenkins-maven-settings/settings.xml/none.xml
  pkg/cmd/populate/test_data/secret-schema.yaml
  pkg/cmd/populate/test_data/secrets/jenkins-x-bucketrepo.yaml
  pkg/cmd/populate/test_data/secrets/lighthouse-hmac-token.yaml
  pkg/cmd/populate/test_data/secrets/lighthouse-oauth-token.yaml
Labels: approved, size/S

#59 fix: handle single property with blank property name on GSM
  pkg/extsecrets/editor/gsm/gsm_editor.go
Labels: approved, lgtm, size/XS

#60 fix: creates resources
  jenkins-x.yml
Labels: approved, size/XS

#61 fix: fix issue with missing version info in binary
  .goreleaser.yml
Labels: approved, lgtm, size/XS

#62 fix: add support for easy secret replication across namespaces
  docs/cmd/jx-secret.md
  docs/cmd/jx-secret_convert.md
  docs/cmd/jx-secret_convert_edit.md
  docs/cmd/jx-secret_edit.md
  docs/cmd/jx-secret_export.md
  docs/cmd/jx-secret_import.md
  docs/cmd/jx-secret_plugins.md
  docs/cmd/jx-secret_plugins_upgrade.md
  docs/cmd/jx-secret_populate.md
  docs/cmd/jx-secret_replicate.md
  docs/cmd/jx-secret_vault.md
  docs/cmd/jx-secret_vault_portforward.md
  docs/cmd/jx-secret_vault_shell.md
  docs/cmd/jx-secret_vault_wait.md
  docs/cmd/jx-secret_verify.md
  docs/cmd/jx-secret_version.md
  docs/cmd/jx-secret_wait.md
  docs/external.md
  docs/man/man1/jx-secret-replicate.1
  docs/man/man1/jx-secret-verify.1
  docs/man/man1/jx-secret.1
  docs/mapping.md
  docs/schema.md
  go.sum
  pkg/cmd/replicate/replicate.go
  pkg/cmd/replicate/replicate_test.go
  pkg/cmd/replicate/test_data/config-root/namespaces/jx/lighthouse/lighthouse-oauth-token.yaml
  pkg/cmd/replicate/test_data/config-root/namespaces/jx/tekton/knative-docker-user-pass.yaml
  pkg/cmd/replicate/test_data/jx-requirements.yml
  pkg/cmd/root.go
  pkg/extsecrets/constants.go
  pkg/extsecrets/editor/local/local_editor.go
  pkg/extsecrets/editor/local/local_editor_test.go
Labels: approved, size/XL

#63 fix: add better defaulting of replication namespaces
  pkg/cmd/replicate/replicate.go
  pkg/cmd/replicate/replicate_test.go
  pkg/cmd/replicate/test_data/config-root/namespaces/jx/jxboot-helmfile-resources/environments.yaml
  pkg/cmd/replicate/test_data/config-root/namespaces/jx/jxboot-helmfile-resources/environments2.yaml
  pkg/cmd/replicate/test_data/config-root/namespaces/jx/jxboot-helmfile-resources/environments3.yaml
Labels: approved, size/L

#64 fix: add better filtering of replicate
  go.mod
  go.sum
  pkg/cmd/replicate/replicate.go
Labels: approved, size/S

#65 fix: for local secret replicatino
  pkg/cmd/populate/populate.go
  pkg/cmd/replicate/replicate.go
  pkg/cmd/replicate/replicate_test.go
  pkg/extsecrets/constants.go
  pkg/extsecrets/editor/local/local_editor.go
  pkg/extsecrets/editor/local/local_editor_test.go
Labels: approved, size/M

#66 fix: add test for selector based secret replication
  docs/cmd/jx-secret.md
  docs/cmd/jx-secret_convert.md
  docs/cmd/jx-secret_convert_edit.md
  docs/cmd/jx-secret_edit.md
  docs/cmd/jx-secret_export.md
  docs/cmd/jx-secret_import.md
  docs/cmd/jx-secret_plugins.md
  docs/cmd/jx-secret_plugins_upgrade.md
  docs/cmd/jx-secret_populate.md
  docs/cmd/jx-secret_replicate.md
  docs/cmd/jx-secret_vault.md
  docs/cmd/jx-secret_vault_portforward.md
  docs/cmd/jx-secret_vault_shell.md
  docs/cmd/jx-secret_vault_wait.md
  docs/cmd/jx-secret_verify.md
  docs/cmd/jx-secret_version.md
  docs/cmd/jx-secret_wait.md
  docs/external.md
  docs/man/man1/jx-secret-replicate.1
  docs/mapping.md
  docs/schema.md
  go.mod
  go.sum
  pkg/cmd/populate/populate.go
  pkg/cmd/replicate/replicate.go
  pkg/cmd/replicate/replicate_test.go
  pkg/cmd/replicate/test_data/config-root/namespaces/jx/lighthouse/lighthouse-hmac-token.yaml
  pkg/cmd/replicate/test_data/config-root/namespaces/jx/lighthouse/lighthouse-oauth-token.yaml
  pkg/cmd/replicate/test_data/config-root/namespaces/jx/tekton/knative-docker-user-pass.yaml
Labels: approved, size/L

#67 fix: add copy command
  docs/cmd/jx-secret.md
  docs/cmd/jx-secret_copy.md
  docs/external.md
  docs/man/man1/jx-secret-copy.1
  docs/man/man1/jx-secret.1
  docs/mapping.md
  docs/schema.md
  pkg/cmd/copy/copy.go
  pkg/cmd/copy/copy_test.go
  pkg/cmd/replicate/replicate_test.go
  pkg/cmd/root.go
  pkg/extsecrets/editor/local/local_editor.go
  pkg/extsecrets/helpers.go
Labels: approved, size/L

#68 fix: lets preserve the labels on the secrets -> ExternalSecrets
  pkg/cmd/convert/convert.go
  pkg/cmd/convert/test_data/backend_types/oauth1/expected.yaml
  pkg/cmd/convert/test_data/backend_types/oauth2/expected.yaml
  pkg/cmd/convert/test_data/simple/hmac/expected.yaml
  pkg/cmd/convert/test_data/simple/oauth/expected.yaml
Labels: approved, size/S

#70 fix: add a lazy create flag to secret copy
  docs/cmd/jx-secret.md
  docs/cmd/jx-secret_convert.md
  docs/cmd/jx-secret_convert_edit.md
  docs/cmd/jx-secret_copy.md
  docs/cmd/jx-secret_edit.md
  docs/cmd/jx-secret_export.md
  docs/cmd/jx-secret_import.md
  docs/cmd/jx-secret_plugins.md
  docs/cmd/jx-secret_plugins_upgrade.md
  docs/cmd/jx-secret_populate.md
  docs/cmd/jx-secret_replicate.md
  docs/cmd/jx-secret_vault.md
  docs/cmd/jx-secret_vault_portforward.md
  docs/cmd/jx-secret_vault_shell.md
  docs/cmd/jx-secret_vault_wait.md
  docs/cmd/jx-secret_verify.md
  docs/cmd/jx-secret_version.md
  docs/cmd/jx-secret_wait.md
  docs/external.md
  docs/man/man1/jx-secret-copy.1
  docs/mapping.md
  docs/schema.md
  pkg/cmd/copy/copy.go
  pkg/cmd/copy/copy_test.go
Labels: approved, size/M

#69 chore: lets default to the current namespace when looking for the boot secret
  pkg/cmd/populate/populate.go
  pkg/cmd/populate/populate_test.go
Labels: approved, lgtm, size/S

#71 chore: bumped jx-api and fixed unit tests to accommodate new jx-requi…
  Dockerfile.preview
  go.mod
  go.sum
  pkg/cmd/populate/test_data/jx-requirements.yml
Labels: approved, ok-to-test, size/S

#72 fix: revert "Merge pull request #71 from chrismellard/azure-secret-key-vault"
  Dockerfile.preview
  go.mod
  go.sum
  pkg/cmd/populate/test_data/jx-requirements.yml
Labels: approved, lgtm, ok-to-test, size/S

#73 fix: upgrade deps
  go.mod
  go.sum
Labels: approved, size/M

#76 fix: avoid building linux binary twice
  Makefile
Labels: approved, lgtm, size/XS
