Repository jenkins-x-plugins/jx-secret, pull requests merged in 2020-10, with the labels that each got.

#91 fix: support discovering secret-schema files outside of the version stream
  README.md
  docs/cmd/jx-secret.md
  docs/cmd/jx-secret_convert.md
  docs/cmd/jx-secret_convert_edit.md
  docs/cmd/jx-secret_copy.md
  docs/cmd/jx-secret_edit.md
  docs/cmd/jx-secret_export.md
  docs/cmd/jx-secret_import.md
  docs/cmd/jx-secret_plugins.md
  docs/cmd/jx-secret_plugins_upgrade.md
  docs/cmd/jx-secret_populate.md
  docs/cmd/jx-secret_replicate.md
  docs/cmd/jx-secret_vault.md
  docs/cmd/jx-secret_vault_portforward.md
  docs/cmd/jx-secret_vault_shell.md
  docs/cmd/jx-secret_vault_wait.md
  docs/cmd/jx-secret_verify.md
  docs/cmd/jx-secret_version.md
  docs/cmd/jx-secret_wait.md
  docs/external.md
  docs/man/man1/jx-secret-convert.1
  docs/man/man1/jx-secret-copy.1
  docs/man/man1/jx-secret-populate.1
  docs/mapping.md
  docs/schema.md
  go.mod
  go.sum
  pkg/cmd/convert/convert.go
  pkg/cmd/convert/convert_test.go
  pkg/cmd/convert/edit/edit.go
  pkg/cmd/convert/test_data/local-schema/.jx/secret/mapping/secret-mappings.yaml
  pkg/cmd/convert/test_data/local-schema/charts/jenkins-x/chartmuseum/secret-schema.yaml
  pkg/cmd/convert/test_data/local-schema/config-root/namespaces/jx/chartmuseum/secret.yaml
  pkg/cmd/convert/test_data/local-schema/config-root/namespaces/jx/jxboot-helmfile-resources/gh-secret.yaml
  pkg/cmd/convert/test_data/local-schema/config-root/namespaces/jx/jxboot-helmfile-resources/maven-settings-secret.yaml
  pkg/cmd/convert/test_data/local-schema/config-root/namespaces/jx/tekton/250-docker-secret.yaml
  pkg/cmd/convert/test_data/local-schema/config-root/namespaces/jx/tekton/250-git-secret.yaml
  pkg/cmd/convert/test_data/local-schema/versionStream/charts/banzaicloud-stable/vault-operator.yml
  pkg/cmd/convert/test_data/local-schema/versionStream/charts/bitnami/external-dns.yml
  pkg/cmd/convert/test_data/local-schema/versionStream/charts/bitnami/external-dns/template-values.yaml
  pkg/cmd/convert/test_data/local-schema/versionStream/charts/external-secrets/kubernetes-external-secrets.yml
  pkg/cmd/convert/test_data/local-schema/versionStream/charts/jenkins-x/chartmuseum/secret-schema.yaml
  pkg/cmd/convert/test_data/local-schema/versionStream/charts/jenkins-x/jxboot-helmfile-resources.yml
  pkg/cmd/convert/test_data/local-schema/versionStream/charts/jenkins-x/jxboot-helmfile-resources/secret-schema.yaml
  pkg/cmd/convert/test_data/local-schema/versionStream/charts/jenkins-x/lighthouse.yml
  pkg/cmd/convert/test_data/local-schema/versionStream/charts/jenkins-x/tekton.yml
  pkg/cmd/convert/test_data/local-schema/versionStream/charts/jenkins-x/tekton/secret-schema.yaml
  pkg/cmd/convert/test_data/local-schema/versionStream/charts/repositories.yml
  pkg/cmd/convert/test_data/local-schema/versionStream/charts/stable/cert-manager.yml
  pkg/cmd/convert/test_data/local-schema/versionStream/values/jenkins-x/tekton/values.yaml.gotmpl
  pkg/cmd/convert/test_data/schema/config-root/namespaces/jx/chartmuseum/secret.yaml
  pkg/cmd/convert/test_data/schema/config-root/namespaces/jx/jxboot-helmfile-resources/gh-secret.yaml
  pkg/cmd/convert/test_data/schema/config-root/namespaces/jx/jxboot-helmfile-resources/maven-settings-secret.yaml
  pkg/cmd/convert/test_data/schema/config-root/namespaces/jx/tekton/250-docker-secret.yaml
  pkg/cmd/convert/test_data/schema/config-root/namespaces/jx/tekton/250-git-secret.yaml
Labels: approved, lgtm, size/L

#94 fix: upgrade sprig
  go.mod
  go.sum
  pkg/cmd/populate/templater.go
Labels: approved, size/M

#95 fix: add htpasswdSecret function
  go.mod
  pkg/cmd/populate/functions.go
  pkg/cmd/populate/templater.go
  pkg/cmd/populate/templater_test.go
  pkg/cmd/populate/templatertesting/run.go
  pkg/cmd/populate/templatertesting/types.go
  pkg/cmd/populate/test_data/expected/jx-basic-auth-htpasswd/auth/jx-basic-auth-htpasswd.txt
  pkg/cmd/populate/test_data/secret-schema.yaml
  pkg/cmd/populate/test_data/secrets/jx-basic-auth-htpasswd.yaml
Labels: approved, size/L

#99 fix: add secret masker
  pkg/masker/dump/main.go
  pkg/masker/masker.go
  pkg/masker/masker_test.go
Labels: approved, size/L

#100 fix: improve the masker logic
  pkg/apis/schema/v1alpha1/types.go
  pkg/cmd/populate/templater.go
  pkg/masker/masker.go
  pkg/masker/watcher/watcher.go
  pkg/masker/watcher/watcher_test.go
Labels: approved, size/L

#101 fix: upgrade deps
  go.mod
  go.sum
Labels: approved, size/M

#102 fix: add helper method
  pkg/masker/watcher/watcher.go
Labels: approved, size/XS

#103 fix: improve output when using watcher
  pkg/masker/masker.go
  pkg/masker/watcher/watcher.go
Labels: approved, size/M

#104 fix: return blank string if we can't create htpasswd
  pkg/cmd/populate/templater.go
Labels: approved, size/S

#105 fix: populate should run twice
  pkg/cmd/populate/populate.go
Labels: approved, size/S

#106 chore: switch to using unstructured functions from jx-helpers
  go.mod
  go.sum
  pkg/extsecrets/client.go
  pkg/extsecrets/knative_pkg/README.md
  pkg/extsecrets/knative_pkg/duck/interface.go
  pkg/extsecrets/knative_pkg/duck/unstructured.go
  pkg/extsecrets/knative_pkg/kmeta/accessor.go
  pkg/extsecrets/knative_pkg/kmeta/owner_references.go
Labels: approved, size/L

#108 fix: lets not convert empty Secret resources to ExternalSecrets by default
  go.sum
  pkg/cmd/convert/convert.go
  pkg/cmd/convert/convert_test.go
  pkg/cmd/convert/test_data/schema/config-root/namespaces/jx/tekton/webhook-certs-secret.yaml
Labels: approved, size/M

#113 fix: support namespace specific secrets
  go.mod
  go.sum
  pkg/cmd/populate/templater.go
  pkg/cmd/populate/templater_test.go
Labels: approved, size/M
