Repository jenkins-x-plugins/jx-secret, pull requests merged in 2020-12, with the labels that each got.

#145 refactor: remove old v2 code
  go.mod
  go.sum
  jx/bdd/boot-lh-ghe/jx-requirements.yml
  jx/bdd/boot-vault/jx-requirements.yml
  pkg/apis/mapping/v1alpha1/types.go
  pkg/cmd/convert/edit/edit.go
  pkg/cmd/convert/edit/test_data/gsm_defaults_add/jx-requirements.yml
  pkg/cmd/convert/edit/test_data/gsm_defaults_dont_replace/jx-requirements.yml
  pkg/cmd/convert/test_data/backend_types/oauth1/expected.yaml
  pkg/cmd/convert/test_data/backend_types/oauth2/expected.yaml
  pkg/cmd/convert/test_data/simple/hmac/expected.yaml
  pkg/cmd/convert/test_data/simple/oauth/expected.yaml
  pkg/cmd/convert/test_data/simple/stringData/expected.yaml
  pkg/cmd/populate/populate.go
  pkg/cmd/populate/templater.go
  pkg/cmd/populate/templater_test.go
  pkg/cmd/populate/templatertesting/types.go
  pkg/cmd/populate/test_data/jx-requirements.yml
  pkg/cmd/replicate/replicate.go
  pkg/cmd/replicate/test_data/jx-requirements.yml
  pkg/plugins/helpers.go
Labels: approved, size/L

#147 refactor: move traditional CRDs back to jenkins.io group so we dont need to create new CRDs
  go.mod
  go.sum
  pkg/cmd/replicate/replicate.go
  pkg/plugins/helpers.go
Labels: approved, size/S

#148 fix: handle no storage as hasKey templating seems to have no affect
  pkg/cmd/populate/templater.go
Labels: approved, size/XS

#151 chore: upgrade pipelines
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
Labels: size/XS, updatebot

#150 feat: added azureKeyVault editor
  go.mod
  go.sum
  pkg/apis/external/v1/types.go
  pkg/extsecrets/editor/azure/azure_editor.go
  pkg/extsecrets/editor/azure/azure_editor_test.go
  pkg/extsecrets/editor/factory/factory.go
Labels: approved, ok-to-test, size/L

#156 feat: added in azure key vault naming defaults
  go.mod
  pkg/apis/mapping/v1alpha1/types.go
  pkg/cmd/convert/convert.go
  pkg/cmd/convert/edit/edit.go
  pkg/cmd/convert/test_data/backend_types/.jx/secret/mapping/secret-mappings.yaml
  pkg/cmd/convert/test_data/backend_types/oauth3/expected.yaml
  pkg/cmd/replicate/replicate.go
Labels: approved, lgtm, ok-to-test, size/M

#161 fix: fixed up error in azure key vault editor
  go.mod
  go.sum
  pkg/extsecrets/editor/azure/azure_editor.go
  pkg/extsecrets/editor/azure/azure_editor_test.go
Labels: approved, lgtm, ok-to-test, size/S

#162 fix: putting mapping in to turn vault name in to vault url
  pkg/extsecrets/editor/azure/azure_editor.go
Labels: approved, lgtm, ok-to-test, size/XS

#163 fix: removed default property to field for Azure key vault so this is directly controlled by secret mapping instead
  pkg/cmd/convert/convert.go
Labels: approved, lgtm, ok-to-test, size/XS

#164 fix: default key name to name of secret
  pkg/cmd/convert/convert.go
Labels: approved, lgtm, ok-to-test, size/XS

#166 fix: fixed up azure key vault behaviour to work with complex and simple secret types
  pkg/cmd/convert/convert.go
  pkg/cmd/convert/convert_test.go
  pkg/cmd/convert/test_data/azure_key_vault/.jx/secret/mapping/secret-mappings.yaml
  pkg/cmd/convert/test_data/azure_key_vault/oauth1/expected.yaml
  pkg/cmd/convert/test_data/azure_key_vault/oauth1/source.yaml
  pkg/cmd/convert/test_data/azure_key_vault/oauth2/expected.yaml
  pkg/cmd/convert/test_data/azure_key_vault/oauth2/source.yaml
  pkg/cmd/convert/test_data/azure_key_vault/oauth3/expected.yaml
  pkg/cmd/convert/test_data/azure_key_vault/oauth3/source.yaml
  pkg/cmd/convert/test_data/azure_key_vault/oauth4/expected.yaml
  pkg/cmd/convert/test_data/azure_key_vault/oauth4/source.yaml
  pkg/cmd/convert/test_data/azure_key_vault/oauth5/expected.yaml
  pkg/cmd/convert/test_data/azure_key_vault/oauth5/source.yaml
  pkg/extsecrets/editor/azure/azure_editor.go
  pkg/extsecrets/editor/azure/azure_editor_test.go
Labels: approved, ok-to-test, size/L

#167 chore: added in retry command helper to jx secret populate that occasionally times out talking with apiserver
  pkg/cmd/populate/populate.go
  pkg/cmd/root.go
Labels: approved, lgtm, ok-to-test, size/S

#168 feat: change populate behaviour so it populates non templated secrets first
  pkg/cmd/populate/templater.go
  pkg/extsecrets/secretfacade/verify_filter.go
Labels: approved, lgtm, ok-to-test, size/M

#169 feat: change populate behaviour so it populates non templated secrets first
  pkg/cmd/populate/templater.go
Labels: approved, lgtm, ok-to-test, size/S

#172 fix: add filter option on populate and verify
  go.mod
  go.sum
  pkg/cmd/convert/convert.go
  pkg/cmd/populate/populate.go
  pkg/cmd/verify/verify.go
  pkg/extsecrets/secretfacade/types.go
  pkg/extsecrets/secretfacade/verify.go
Labels: approved, size/S

#176 feat: increasing verbosity of logging output during secret template function retry backoff loops. Increased backoff durationt to give ExternalSecrets more time to create the Secret
  pkg/cmd/populate/populate.go
  pkg/cmd/populate/populate_test.go
  pkg/cmd/populate/templater.go
Labels: approved, ok-to-test, size/M

#177 fix: disable retry on templates by default
  go.mod
  go.sum
  pkg/apis/schema/v1alpha1/types.go
  pkg/cmd/populate/populate.go
  pkg/cmd/populate/templater.go
  pkg/cmd/populate/templatertesting/run.go
Labels: approved, size/M

#183 feat: added ability to retain pseudo secrets in repo if they are explicitly marked in secret mapping config
  go.mod
  go.sum
  pkg/apis/mapping/v1alpha1/types.go
  pkg/cmd/convert/convert.go
  pkg/cmd/convert/convert_test.go
  pkg/cmd/convert/test_data/unsecureSecrets/.jx/secret/mapping/secret-mappings.yaml
  pkg/cmd/convert/test_data/unsecureSecrets/compositeOauth/expected.yaml
  pkg/cmd/convert/test_data/unsecureSecrets/compositeOauth/source.yaml
  pkg/cmd/convert/test_data/unsecureSecrets/hmac/expected.yaml
  pkg/cmd/convert/test_data/unsecureSecrets/hmac/source.yaml
  pkg/cmd/convert/test_data/unsecureSecrets/oauth/expected.yaml
  pkg/cmd/convert/test_data/unsecureSecrets/oauth/source.yaml
  pkg/cmd/convert/test_data/unsecureSecrets/stringData/expected.yaml
  pkg/cmd/convert/test_data/unsecureSecrets/stringData/source.yaml
Labels: approved, lgtm, ok-to-test, size/L

#186 fix: fixed issue where mandatory external secret spec.data field could be missing during convert
  pkg/cmd/convert/convert.go
  pkg/cmd/convert/test_data/unsecureSecrets/oauth/expected.yaml
Labels: approved, lgtm, ok-to-test, size/S
