Repository jenkins-x-plugins/jx-secret, pull requests merged in 2020-08, with the labels that each got.

#14 feat: add a survey schema to easily prompt for user data such as secrets
  go.mod
  go.sum
  pkg/cmd/edit/edit.go
  pkg/extsecrets/editor/factory/factory.go
  pkg/extsecrets/editor/gsm/gsm_editor.go
  pkg/schema/doc.go
  pkg/schema/helpers.go
  pkg/schema/helpers_test.go
  pkg/schema/schema.go
  pkg/schema/test_data/load/schema.yaml
  pkg/schema/test_data/validate/schema.yaml
Labels: approved, lgtm, size/L

#17 fix: add generator for gitOperator user/password
  pkg/cmd/edit/edit.go
  pkg/cmd/populate/populate.go
  pkg/cmd/populate/populate_test.go
  pkg/cmd/populate/test_data/.jx/gitops/secret-schema.yaml
  pkg/schema/generators/hmac.go
  pkg/schema/generators/password.go
  pkg/schema/generators/secret_entry.go
  pkg/schema/generators/types.go
  pkg/schema/helpers.go
  pkg/schema/schema.go
  pkg/schema/testschemas/helpers.go
Labels: approved, size/L

#18 fix: some bugs in secret population
  go.mod
  pkg/cmd/edit/edit_test.go
  pkg/cmd/export/export_test.go
  pkg/cmd/import/import.go
  pkg/cmd/import/import_test.go
  pkg/cmd/populate/populate_test.go
  pkg/cmd/vault/portforward/vault_portforward_test.go
  pkg/cmd/vault/wait/vault_wait.go
  pkg/cmd/vault/wait/vault_wait_test.go
  pkg/cmd/verify/verify_test.go
  pkg/extsecrets/helpers.go
  pkg/extsecrets/secretfacade/load.go
  pkg/schema/generators/secret_entry.go
Labels: approved, size/M

#19 docs: regenerate the docs
  docs/cmd/jx-secret.md
  docs/cmd/jx-secret_edit.md
  docs/cmd/jx-secret_export.md
  docs/cmd/jx-secret_import.md
  docs/cmd/jx-secret_plugins.md
  docs/cmd/jx-secret_plugins_upgrade.md
  docs/cmd/jx-secret_populate.md
  docs/cmd/jx-secret_vault.md
  docs/cmd/jx-secret_vault_portforward.md
  docs/cmd/jx-secret_vault_wait.md
  docs/cmd/jx-secret_verify.md
  docs/cmd/jx-secret_version.md
  docs/man/man1/jx-secret-edit.1
  docs/man/man1/jx-secret-plugins-upgrade.1
  docs/man/man1/jx-secret-plugins.1
  docs/man/man1/jx-secret-populate.1
  docs/man/man1/jx-secret.1
  go.mod
  go.sum
Labels: approved, size/L

#20 fix: lets wait for backend before creating editor
  go.mod
  go.sum
  pkg/cmd/populate/populate.go
Labels: approved, size/S

#21 fix: add more logging to secret step
  pkg/schema/generators/secret_entry.go
Labels: approved, size/S

#22 fix: add wait function and better edit
  pkg/cmd/edit/edit.go
  pkg/cmd/edit/edit_test.go
  pkg/cmd/import/import.go
  pkg/cmd/populate/populate.go
  pkg/cmd/root.go
  pkg/cmd/verify/verify.go
  pkg/cmd/wait/test_data/knative-docker-user-pass.yaml
  pkg/cmd/wait/test_data/lighthouse-oauth-token.yaml
  pkg/cmd/wait/wait.go
  pkg/cmd/wait/wait_test.go
  pkg/extsecrets/constants.go
  pkg/extsecrets/editor/gsm/gsm_editor.go
  pkg/extsecrets/editor/interface.go
  pkg/extsecrets/editor/vault/vault_editor.go
  pkg/extsecrets/secretfacade/types.go
  pkg/extsecrets/secretfacade/verify.go
Labels: approved, size/L

#23 fix: timeout config bug
  pkg/cmd/wait/wait.go
Labels: approved, size/S

#24 fix: add better waiting logic for vault
  pkg/cmd/vault/portforward/vault_portforward.go
  pkg/cmd/vault/wait/vault_wait.go
  pkg/cmd/vault/wait/vault_wait_test.go
  pkg/cmd/wait/wait.go
  pkg/extsecrets/editor/vault/vault_editor.go
  pkg/extsecrets/editor/vault/vault_editor_test.go
Labels: approved, size/L

#27 fix: added schema discovery
  README.md
  docs/README.md
  docs/cmd/jx-secret_convert.md
  docs/external.md
  docs/man/man1/jx-secret-convert.1
  docs/mapping.md
  docs/schema.md
  go.sum
  pkg/apis/mapping/v1alpha1/types.go
  pkg/apis/schema/v1alpha1/types.go
  pkg/cmd/convert/convert.go
  pkg/cmd/convert/convert_test.go
  pkg/cmd/convert/edit/test_data/gsm_defaults_add/.jx/secret/mapping/secret-mappings.yaml
  pkg/cmd/convert/edit/test_data/gsm_defaults_dont_replace/.jx/secret/mapping/secret-mappings.yaml
  pkg/cmd/convert/test_data/backend_types/.jx/secret/mapping/secret-mappings.yaml
  pkg/cmd/convert/test_data/schema/.jx/secret/mapping/secret-mappings.yaml
  pkg/cmd/convert/test_data/schema/somedir/namespaces/jx/chartmuseum/secret.yaml
  pkg/cmd/convert/test_data/schema/somedir/namespaces/jx/jxboot-helmfile-resources/gh-secret.yaml
  pkg/cmd/convert/test_data/schema/somedir/namespaces/jx/jxboot-helmfile-resources/maven-settings-secret.yaml
  pkg/cmd/convert/test_data/schema/somedir/namespaces/jx/tekton/250-docker-secret.yaml
  pkg/cmd/convert/test_data/schema/somedir/namespaces/jx/tekton/250-git-secret.yaml
  pkg/cmd/convert/test_data/schema/versionStream/charts/banzaicloud-stable/vault-operator.yml
  pkg/cmd/convert/test_data/schema/versionStream/charts/bitnami/external-dns.yml
  pkg/cmd/convert/test_data/schema/versionStream/charts/bitnami/external-dns/template-values.yaml
  pkg/cmd/convert/test_data/schema/versionStream/charts/external-secrets/kubernetes-external-secrets.yml
  pkg/cmd/convert/test_data/schema/versionStream/charts/jenkins-x/chartmuseum/secret-schema.yaml
  pkg/cmd/convert/test_data/schema/versionStream/charts/jenkins-x/jxboot-helmfile-resources.yml
  pkg/cmd/convert/test_data/schema/versionStream/charts/jenkins-x/jxboot-helmfile-resources/secret-schema.yaml
  pkg/cmd/convert/test_data/schema/versionStream/charts/jenkins-x/lighthouse.yml
  pkg/cmd/convert/test_data/schema/versionStream/charts/jenkins-x/tekton.yml
  pkg/cmd/convert/test_data/schema/versionStream/charts/jenkins-x/tekton/secret-schema.yaml
  pkg/cmd/convert/test_data/schema/versionStream/charts/repositories.yml
  pkg/cmd/convert/test_data/schema/versionStream/charts/stable/cert-manager.yml
  pkg/cmd/convert/test_data/schema/versionStream/values/jenkins-x/tekton/values.yaml.gotmpl
  pkg/cmd/convert/test_data/simple/.jx/secret/mapping/secret-mappings.yaml
  pkg/cmd/convert/test_data/simple/oauth/expected.yaml
  pkg/cmd/convert/test_data/validation/.jx/secret/mapping/secret-mappings.yaml
  pkg/cmd/edit/edit.go
  pkg/cmd/populate/populate.go
  pkg/cmd/populate/test_data/.jx/secret/schema/secret-schema.yaml
  pkg/cmd/wait/test_data/knative-docker-user-pass.yaml
  pkg/cmd/wait/test_data/lighthouse-oauth-token.yaml
  pkg/extsecrets/constants.go
  pkg/extsecrets/secretfacade/types.go
  pkg/schema/helpers.go
  pkg/schemas/doc.go
  pkg/schemas/generators/hmac.go
  pkg/schemas/generators/password.go
  pkg/schemas/generators/secret_entry.go
  pkg/schemas/generators/types.go
  pkg/schemas/helpers.go
  pkg/schemas/helpers_test.go
  pkg/schemas/secrets/secrets.go
  pkg/schemas/test_data/load/schema.yaml
  pkg/schemas/test_data/validate/schema.yaml
  pkg/schemas/testschemas/helpers.go
  pkg/secretmapping/helpers.go
  pkg/secretmapping/test_data/.jx/secret/mapping/secret-mappings.yaml
  pkg/secretmapping/test_data/missing_default_backend_type/.jx/secret/mapping/secret-mappings.yaml
Labels: approved, size/XL

#28 fix: removed the old loading of the schema files
  README.md
  docs/cmd/jx-secret.md
  docs/cmd/jx-secret_convert.md
  docs/cmd/jx-secret_convert_edit.md
  docs/cmd/jx-secret_edit.md
  docs/cmd/jx-secret_export.md
  docs/cmd/jx-secret_import.md
  docs/cmd/jx-secret_plugins.md
  docs/cmd/jx-secret_plugins_upgrade.md
  docs/cmd/jx-secret_populate.md
  docs/cmd/jx-secret_vault.md
  docs/cmd/jx-secret_vault_portforward.md
  docs/cmd/jx-secret_vault_wait.md
  docs/cmd/jx-secret_verify.md
  docs/cmd/jx-secret_version.md
  docs/cmd/jx-secret_wait.md
  docs/external.md
  docs/man/man1/jx-secret-edit.1
  docs/man/man1/jx-secret-populate.1
  docs/mapping.md
  docs/schema.md
  pkg/apis/schema/v1alpha1/types.go
  pkg/cmd/convert/convert.go
  pkg/cmd/convert/convert_test.go
  pkg/cmd/convert/edit/edit.go
  pkg/cmd/edit/edit.go
  pkg/cmd/populate/populate.go
  pkg/cmd/populate/test_data/.jx/secret/schema/secret-schema.yaml
  pkg/cmd/populate/test_data/jenkins-x-bucketrepo.yaml
  pkg/cmd/populate/test_data/knative-docker-user-pass.yaml
  pkg/cmd/populate/test_data/lighthouse-hmac-token.yaml
  pkg/cmd/populate/test_data/lighthouse-oauth-token.yaml
  pkg/cmd/wait/test_data/knative-docker-user-pass.yaml
  pkg/cmd/wait/test_data/lighthouse-oauth-token.yaml
  pkg/extsecrets/constants.go
  pkg/extsecrets/secretfacade/types.go
  pkg/extsecrets/secretfacade/verify.go
  pkg/schemas/generators/types.go
  pkg/schemas/helpers.go
  pkg/schemas/testschemas/helpers.go
Labels: approved, size/L

#29 fix: switch to secret-infra ns
  pkg/apis/mapping/v1alpha1/types.go
  pkg/cmd/convert/convert.go
  pkg/cmd/convert/test_data/backend_types/oauth1/expected.yaml
  pkg/cmd/convert/test_data/simple/hmac/expected.yaml
  pkg/cmd/convert/test_data/simple/oauth/expected.yaml
  pkg/cmd/vault/portforward/vault_portforward_test.go
  pkg/cmd/vault/shell/shell.go
  pkg/cmd/vault/shell/shell_test.go
  pkg/cmd/vault/wait/vault_wait.go
  pkg/cmd/vault/wait/vault_wait_test.go
  pkg/extsecrets/editor/vault/vault_editor.go
  pkg/extsecrets/secretfacade/test_data/.jx/secret/mapping/secret-mappings.yaml
  pkg/extsecrets/secretfacade/test_data/jxboot-helmfile-resources-pipeline-secret.yaml
  pkg/extsecrets/secretfacade/test_data/lighthouse-hmac-token.yaml
  pkg/extsecrets/secretfacade/test_data/lighthouse-oauth-token.yaml
  pkg/extsecrets/secretfacade/test_data/tekton-docker-secret.yaml
  pkg/extsecrets/secretfacade/test_data/tekton-gh-secret.yaml
  pkg/extsecrets/secretfacade/types.go
  pkg/extsecrets/secretfacade/verify.go
  pkg/extsecrets/secretfacade/verify_filter.go
  pkg/extsecrets/secretfacade/verify_filter_test.go
  pkg/extsecrets/testsecrets/vault.go
  pkg/vaults/constants.go
  pkg/vaults/vaultcli/helpers.go
Labels: approved, size/XL

#34 fix: handle stringData secrets
  README.md
  pkg/apis/external/v1/types.go
  pkg/cmd/convert/convert.go
  pkg/cmd/convert/test_data/simple/stringData/expected.yaml
  pkg/cmd/convert/test_data/simple/stringData/source.yaml
  pkg/cmd/verify/verify.go
  pkg/cmd/wait/wait.go
Labels: approved, size/L

#33 chore: lets use Jenkins X requirements to edit any missing secret mappings
  go.sum
  pkg/cmd/convert/edit/edit.go
  pkg/cmd/convert/edit/edit_test.go
  pkg/cmd/convert/edit/test_data/gsm_defaults_add/jx-requirements.yml
  pkg/cmd/convert/edit/test_data/gsm_defaults_dont_replace/jx-requirements.yml
Labels: approved, lgtm, size/M

#36 feat: get jx step populate working with google secrets manager
  go.mod
  go.sum
  jenkins-x.yml
  pkg/apis/external/v1/types.go
  pkg/cmd/edit/edit.go
  pkg/cmd/populate/populate.go
  pkg/extsecrets/editor/gsm/gsm_editor.go
  pkg/extsecrets/editor/gsm/gsm_editor_test.go
  pkg/extsecrets/editor/gsm/test_data/write_secrets/expected.json
  pkg/extsecrets/editor/interface.go
Labels: approved, lgtm, size/L

#39 fix: release pipeline
  jenkins-x.yml
Labels: size/XS

#40 fix: added test case to ensure we don't regenerate secrets that have values
  jenkins-x.yml
  pkg/apis/external/v1/types.go
  pkg/cmd/populate/populate.go
  pkg/cmd/populate/populate_test.go
  pkg/extsecrets/testsecrets/load_fake_vault.go
  promote.sh
Labels: approved, size/L

#41 fix: add more sophisticated secret templating
  jenkins-x.yml
  pkg/cmd/populate/populate.go
  pkg/cmd/populate/populate_test.go
  pkg/cmd/populate/templater.go
  pkg/cmd/populate/templater_test.go
  pkg/cmd/populate/templatertesting/helpers.go
  pkg/cmd/populate/templatertesting/run.go
  pkg/cmd/populate/templatertesting/types.go
  pkg/cmd/populate/test_data/expected-maven-settings.xml
  pkg/cmd/populate/test_data/expected/jenkins-docker-cfg/config.json/docker-gke.json
  pkg/cmd/populate/test_data/expected/jenkins-maven-settings/settingsXml/bucketrepo.xml
  pkg/cmd/populate/test_data/expected/jenkins-maven-settings/settingsXml/nexus.xml
  pkg/cmd/populate/test_data/expected/jenkins-maven-settings/settingsXml/none.xml
  pkg/cmd/populate/test_data/jx-requirements.yml
  pkg/cmd/populate/test_data/secret-schema.yaml
Labels: approved, size/XXL

#42 fix: lets annotate the Secrets with the schema
  docs/cmd/jx-secret.md
  docs/cmd/jx-secret_convert.md
  docs/cmd/jx-secret_convert_edit.md
  docs/cmd/jx-secret_edit.md
  docs/cmd/jx-secret_export.md
  docs/cmd/jx-secret_import.md
  docs/cmd/jx-secret_plugins.md
  docs/cmd/jx-secret_plugins_upgrade.md
  docs/cmd/jx-secret_populate.md
  docs/cmd/jx-secret_vault.md
  docs/cmd/jx-secret_vault_portforward.md
  docs/cmd/jx-secret_vault_shell.md
  docs/cmd/jx-secret_vault_wait.md
  docs/cmd/jx-secret_verify.md
  docs/cmd/jx-secret_version.md
  docs/cmd/jx-secret_wait.md
  docs/external.md
  docs/mapping.md
  docs/schema.md
  pkg/apis/mapping/v1alpha1/types.go
  pkg/cmd/convert/convert.go
  pkg/cmd/convert/edit/edit.go
  pkg/cmd/populate/templatertesting/run.go
Labels: approved, size/M

#48 fix: handle multiple namespaces better
  pkg/cmd/verify/verify.go
  pkg/extsecrets/secretfacade/load.go
Labels: approved, size/S

#49 fix: handle all namespaces better
  pkg/cmd/populate/populate.go
  pkg/cmd/populate/templater.go
  pkg/cmd/populate/templatertesting/run.go
Labels: approved, size/S

#52 fix: default the namespace to find the boot secret
  go.mod
  go.sum
  pkg/cmd/edit/edit.go
  pkg/cmd/edit/edit_test.go
  pkg/cmd/edit/test_data/local/knative-docker-user-pass.yaml
  pkg/cmd/edit/test_data/local/lighthouse-oauth-token.yaml
  pkg/cmd/edit/test_data/vault/knative-docker-user-pass.yaml
  pkg/cmd/edit/test_data/vault/lighthouse-oauth-token.yaml
  pkg/cmd/import/import.go
  pkg/cmd/populate/populate.go
  pkg/extsecrets/editor/factory/factory.go
  pkg/extsecrets/editor/local/local_editor.go
  pkg/extsecrets/editor/local/local_editor_test.go
  pkg/extsecrets/secretfacade/load.go
  pkg/extsecrets/secretfacade/types.go
Labels: approved, size/L

#53 fix: add default property if property is blank
  pkg/cmd/edit/edit.go
Labels: approved, size/XS

#55 fix: improve local secret support
  pkg/apis/mapping/v1alpha1/types.go
  pkg/cmd/convert/convert.go
Labels: approved, size/S

#56 fix: for local secret population
  pkg/extsecrets/editor/local/local_editor.go
  pkg/extsecrets/editor/local/local_editor_test.go
Labels: approved, size/M

#57 fix: mapping for local secrets
  pkg/cmd/convert/convert.go
Labels: approved, size/S
