Repository jenkins-x-plugins/jx-secret, pull requests merged in 2020-11, with the labels that each got.

#122 chore: fix blocking sonarcloud issues
  pkg/cmd/edit/edit_test.go
  pkg/masker/masker.go
Labels: approved, size/XS

#126 chore: bump jx-api version
  Dockerfile.preview
  go.mod
  go.sum
Labels: approved, ok-to-test, size/S

#128 fix: allow a side car to be used if enabled with env vars
  pkg/cmd/populate/populate.go
  pkg/extsecrets/editor/gsm/gsm_editor.go
Labels: approved, size/M

#130 fix: support an optional temp dir for secrets
  pkg/extsecrets/editor/gsm/gsm_editor.go
Labels: approved, size/S

#129 fix: fixed up so no mandatory externalsecrets allows completion
  pkg/cmd/wait/wait.go
Labels: approved, lgtm, ok-to-test, size/XS

#131 fix: avoid possible exception
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/triggers.yaml
  docs/cmd/jx-secret.md
  docs/cmd/jx-secret_convert.md
  docs/cmd/jx-secret_convert_edit.md
  docs/cmd/jx-secret_copy.md
  docs/cmd/jx-secret_edit.md
  docs/cmd/jx-secret_export.md
  docs/cmd/jx-secret_import.md
  docs/cmd/jx-secret_plugins.md
  docs/cmd/jx-secret_plugins_upgrade.md
  docs/cmd/jx-secret_populate.md
  docs/cmd/jx-secret_replicate.md
  docs/cmd/jx-secret_vault.md
  docs/cmd/jx-secret_vault_portforward.md
  docs/cmd/jx-secret_vault_shell.md
  docs/cmd/jx-secret_vault_wait.md
  docs/cmd/jx-secret_verify.md
  docs/cmd/jx-secret_version.md
  docs/cmd/jx-secret_wait.md
  docs/external.md
  docs/man/man1/jx-secret-replicate.1
  docs/mapping.md
  docs/schema.md
  pkg/cmd/edit/edit.go
  pkg/cmd/edit/edit_test.go
  pkg/cmd/import/import.go
  pkg/cmd/import/import_test.go
  pkg/cmd/populate/populate.go
  pkg/cmd/replicate/replicate.go
  pkg/cmd/vault/wait/vault_wait.go
  pkg/cmd/vault/wait/vault_wait_test.go
  pkg/extsecrets/editor/factory/factory.go
  pkg/extsecrets/editor/gsm/gsm_editor.go
  pkg/extsecrets/editor/vault/vault_editor.go
Labels: approved, do-not-merge/hold, size/L

#138 fix: add a prefix to vault mappings
  pkg/cmd/convert/convert.go
Labels: approved, lgtm, ok-to-test, size/S
