Repository jenkins-x-plugins/jx-secret, pull requests merged in 2021-02, with the labels that each got.

#247 chore: dep bump
  go.mod
Labels: approved, lgtm, ok-to-test, size/XS

#249 chore: really bump deps this time
  go.mod
  go.sum
  pkg/cmd/populate/populate.go
  pkg/cmd/populate/populate_test.go
  pkg/cmd/populate/templater.go
  pkg/cmd/populate/templater_test.go
  pkg/cmd/populate/templatertesting/run.go
  pkg/cmd/populate/templatertesting/types.go
  pkg/extsecrets/secretfacade/types.go
Labels: approved, lgtm, ok-to-test, size/S

#251 fix: broken links
  README.md
Labels: needs-ok-to-test, size/XS

#258 chore: update default vault namespace
  docs/cmd/jx-secret_convert.md
  docs/cmd/jx-secret_vault_portforward.md
  docs/cmd/jx-secret_vault_shell.md
  docs/cmd/jx-secret_vault_wait.md
  go.mod
  go.sum
  pkg/cmd/convert/test_data/backend_types/oauth1/expected.yaml
  pkg/cmd/convert/test_data/simple/hmac/expected.yaml
  pkg/cmd/convert/test_data/simple/oauth/expected.yaml
  pkg/cmd/convert/test_data/simple/stringData/expected.yaml
  pkg/cmd/convert/test_data/unsecureSecrets/compositeOauth/expected.yaml
  pkg/cmd/convert/test_data/unsecureSecrets/hmac/expected.yaml
  pkg/cmd/convert/test_data/unsecureSecrets/oauth/expected.yaml
  pkg/cmd/convert/test_data/unsecureSecrets/stringData/expected.yaml
  pkg/cmd/populate/test_data/populate/vaultsecrets/jenkins-maven-settings.yaml
  pkg/cmd/replicate/test_data/config-root/namespaces/jx/lighthouse/lighthouse-hmac-token.yaml
  pkg/vaults/constants.go
Labels: approved, lgtm, ok-to-test, size/M

#265 feat: rewrote ext secret template functions to query ExternalSecret spec to determine backend secret storage location
  pkg/apis/external/v1/types.go
  pkg/cmd/populate/populate.go
  pkg/cmd/populate/populate_test.go
  pkg/cmd/populate/templater.go
  pkg/cmd/populate/templater_test.go
  pkg/cmd/populate/templatertesting/run.go
  pkg/cmd/populate/templatertesting/types.go
  pkg/cmd/populate/test_data/populate/azuresecrets/gpg.yaml
  pkg/cmd/populate/test_data/populate/azuresecrets/jenkins-maven-settings.yaml
  pkg/cmd/populate/test_data/populate/azuresecrets/jenkins-x-bucketrepo.yaml
  pkg/cmd/populate/test_data/populate/azuresecrets/jx-basic-auth-htpasswd.yaml
  pkg/cmd/populate/test_data/populate/azuresecrets/knative-docker-user-pass.yaml
  pkg/cmd/populate/test_data/populate/azuresecrets/lighthouse-hmac-token.yaml
  pkg/cmd/populate/test_data/populate/azuresecrets/lighthouse-oauth-token.yaml
  pkg/cmd/populate/test_data/populate/azuresecrets/nexus.yaml
  pkg/cmd/populate/test_data/populate/azuresecrets/sonatype.yaml
  pkg/cmd/populate/test_data/populate/expected/jenkins-maven-settings/settings.xml/nexus.xml
  pkg/cmd/populate/test_data/populate/gsmsecrets/gpg.yaml
  pkg/cmd/populate/test_data/populate/gsmsecrets/jenkins-maven-settings.yaml
  pkg/cmd/populate/test_data/populate/gsmsecrets/jenkins-x-bucketrepo.yaml
  pkg/cmd/populate/test_data/populate/gsmsecrets/jx-basic-auth-htpasswd.yaml
  pkg/cmd/populate/test_data/populate/gsmsecrets/knative-docker-user-pass.yaml
  pkg/cmd/populate/test_data/populate/gsmsecrets/lighthouse-hmac-token.yaml
  pkg/cmd/populate/test_data/populate/gsmsecrets/lighthouse-oauth-token.yaml
  pkg/cmd/populate/test_data/populate/gsmsecrets/nexus.yaml
  pkg/cmd/populate/test_data/populate/gsmsecrets/sonatype.yaml
  pkg/cmd/populate/test_data/populate/kubesecrets/gpg.yaml
  pkg/cmd/populate/test_data/populate/kubesecrets/nexus.yaml
  pkg/cmd/populate/test_data/populate/kubesecrets/sonatype.yaml
  pkg/cmd/populate/test_data/populate/secret-schema.yaml
  pkg/cmd/populate/test_data/populate/vaultsecrets/gpg.yaml
  pkg/cmd/populate/test_data/populate/vaultsecrets/nexus.yaml
  pkg/cmd/populate/test_data/populate/vaultsecrets/sonatype.yaml
  pkg/extsecrets/secretfacade/types.go
Labels: approved, lgtm, ok-to-test, size/XL

#275 fix: tone down logging
  go.mod
  go.sum
  pkg/cmd/populate/templater.go
  pkg/schemas/generators/secret_entry.go
Labels: approved, size/M

#276 fix: lets not cause `jx secret populate` to fail
  pkg/extsecrets/file_client.go
Labels: approved, size/XS

#280 fix: add automatic population of external secret stores
  go.mod
  go.sum
  pkg/cmd/edit/edit.go
  pkg/cmd/populate/populate.go
  pkg/cmd/populate/populate_test.go
  pkg/cmd/populate/test_data/populate_helm_secrets/extsecrets/lighthouse-oauth-token.yaml
  pkg/cmd/populate/test_data/populate_helm_secrets/fake-helm-secrets/jx/lighthouse-oauth-token.yaml
  pkg/cmd/populate/test_data/populate_helm_secrets/jx-requirements.yml
Labels: approved, size/L

#281 fix: lets support populating the helm secrets folder in the convert step
  docs/cmd/jx-secret.md
  docs/cmd/jx-secret_convert.md
  docs/cmd/jx-secret_convert_edit.md
  docs/cmd/jx-secret_copy.md
  docs/cmd/jx-secret_edit.md
  docs/cmd/jx-secret_export.md
  docs/cmd/jx-secret_import.md
  docs/cmd/jx-secret_plugins.md
  docs/cmd/jx-secret_plugins_upgrade.md
  docs/cmd/jx-secret_populate.md
  docs/cmd/jx-secret_replicate.md
  docs/cmd/jx-secret_vault.md
  docs/cmd/jx-secret_vault_portforward.md
  docs/cmd/jx-secret_vault_shell.md
  docs/cmd/jx-secret_vault_wait.md
  docs/cmd/jx-secret_verify.md
  docs/cmd/jx-secret_version.md
  docs/cmd/jx-secret_wait.md
  docs/external.md
  docs/man/man1/jx-secret-convert.1
  docs/man/man1/jx-secret-edit.1
  docs/man/man1/jx-secret-populate.1
  docs/man/man1/jx-secret-vault-portforward.1
  docs/man/man1/jx-secret-vault-shell.1
  docs/man/man1/jx-secret-vault-wait.1
  docs/man/man1/jx-secret-verify.1
  docs/mapping.md
  docs/schema.md
  pkg/cmd/convert/convert.go
  pkg/cmd/convert/convert_test.go
  pkg/cmd/populate/populate.go
  pkg/extsecrets/helpers.go
Labels: approved, size/L
