Repository jenkins-x-plugins/jx-secret, pull requests merged in 2021-03, with the labels that each got.

#284 fix: lets tone down the logging
  go.mod
  go.sum
  pkg/cmd/convert/convert.go
  pkg/cmd/convert/edit/edit.go
  pkg/cmd/populate/populate.go
  pkg/cmd/replicate/replicate.go
Labels: approved, size/S

#290 fix: support populating from helm secrets with stringData
  pkg/cmd/populate/populate.go
  pkg/cmd/populate/populate_test.go
  pkg/cmd/populate/test_data/populate_helm_secrets/extsecrets/secret-with-stringdata.yaml
  pkg/cmd/populate/test_data/populate_helm_secrets/fake-helm-secrets/jx/secret-with-stringdata.yaml
Labels: approved, lgtm, ok-to-test, size/M

#292 chore: bump helpers
  go.mod
  go.sum
Labels: approved, size/XS

#293 fix: avoid retry loop when using local secrets
  pkg/cmd/populate/templater.go
Labels: approved, size/S

#297 chore: upgrade deps
  go.mod
  go.sum
Labels: approved, size/S

#298 chore: improve the test framework
  pkg/cmd/populate/templater.go
  pkg/cmd/populate/templatertesting/run.go
  pkg/cmd/populate/templatertesting/types.go
Labels: approved, size/M
