Repository jenkins-x-plugins/jx-secret, pull requests merged in 2021-06, with the labels that each got.

#337 chore: upgrade deps
  docs/cmd/jx-secret.md
  docs/cmd/jx-secret_convert.md
  docs/cmd/jx-secret_convert_edit.md
  docs/cmd/jx-secret_copy.md
  docs/cmd/jx-secret_edit.md
  docs/cmd/jx-secret_export.md
  docs/cmd/jx-secret_import.md
  docs/cmd/jx-secret_plugins.md
  docs/cmd/jx-secret_plugins_upgrade.md
  docs/cmd/jx-secret_populate.md
  docs/cmd/jx-secret_replicate.md
  docs/cmd/jx-secret_vault.md
  docs/cmd/jx-secret_vault_portforward.md
  docs/cmd/jx-secret_vault_shell.md
  docs/cmd/jx-secret_vault_wait.md
  docs/cmd/jx-secret_verify.md
  docs/cmd/jx-secret_version.md
  docs/cmd/jx-secret_wait.md
  docs/external.md
  docs/mapping.md
  docs/schema.md
  go.mod
  go.sum
Labels: approved, size/M

#339 chore: upgrade deps
  go.mod
  go.sum
Labels: approved, size/XS

#341 fix: Make vault shell command work
  pkg/cmd/vault/shell/shell.go
Labels: approved, lgtm, ok-to-test, size/S
