Repository jenkins-x-plugins/jx-secret, pull requests merged in 2021-04, with the labels that each got.

#312 chore: upgrade deps
  go.mod
  go.sum
Labels: approved, size/S

#314 fix: handle local secrets and TLS secrets
  docs/cmd/jx-secret.md
  docs/cmd/jx-secret_convert.md
  docs/cmd/jx-secret_convert_edit.md
  docs/cmd/jx-secret_copy.md
  docs/cmd/jx-secret_edit.md
  docs/cmd/jx-secret_export.md
  docs/cmd/jx-secret_import.md
  docs/cmd/jx-secret_plugins.md
  docs/cmd/jx-secret_plugins_upgrade.md
  docs/cmd/jx-secret_populate.md
  docs/cmd/jx-secret_replicate.md
  docs/cmd/jx-secret_vault.md
  docs/cmd/jx-secret_vault_portforward.md
  docs/cmd/jx-secret_vault_shell.md
  docs/cmd/jx-secret_vault_wait.md
  docs/cmd/jx-secret_verify.md
  docs/cmd/jx-secret_version.md
  docs/cmd/jx-secret_wait.md
  docs/external.md
  docs/mapping.md
  docs/schema.md
  go.mod
  go.sum
  pkg/cmd/edit/edit.go
  pkg/cmd/populate/populate.go
Labels: approved, size/M

#315 fix: jx secret populate for local secrets
  pkg/cmd/populate/populate.go
Labels: approved, size/XS

#316 fix: use correct docs
  docs/cmd/jx-secret.md
  docs/cmd/jx-secret_convert.md
  docs/cmd/jx-secret_convert_edit.md
  docs/cmd/jx-secret_copy.md
  docs/cmd/jx-secret_edit.md
  docs/cmd/jx-secret_export.md
  docs/cmd/jx-secret_import.md
  docs/cmd/jx-secret_plugins.md
  docs/cmd/jx-secret_plugins_upgrade.md
  docs/cmd/jx-secret_populate.md
  docs/cmd/jx-secret_replicate.md
  docs/cmd/jx-secret_vault.md
  docs/cmd/jx-secret_vault_portforward.md
  docs/cmd/jx-secret_vault_shell.md
  docs/cmd/jx-secret_vault_wait.md
  docs/cmd/jx-secret_verify.md
  docs/cmd/jx-secret_version.md
  docs/cmd/jx-secret_wait.md
  docs/external.md
  docs/man/man1/jx-secret-export.1
  docs/mapping.md
  docs/schema.md
  go.mod
  go.sum
  pkg/cmd/edit/edit.go
  pkg/cmd/export/export.go
  pkg/cmd/import/import.go
Labels: approved, size/L

#317 fix: lets not overwrite existing secrets when editing them in GSM
  go.mod
  pkg/extsecrets/editor/gsm/gsm_editor.go
  pkg/extsecrets/editor/gsm/gsm_editor_test.go
  pkg/extsecrets/editor/gsm/test_data/write_secrets/expected.json
  pkg/extsecrets/editor/gsm/test_data/write_single/expected.json
Labels: approved, size/M

#318 chore: upgrade deps
  go.mod
  go.sum
Labels: approved, size/XS

#319 fix: lets allow a Secret schema to disable template regen
  go.mod
  go.sum
  pkg/apis/schema/v1alpha1/types.go
  pkg/cmd/convert/convert.go
  pkg/cmd/convert/convert_test.go
  pkg/cmd/convert/edit/edit.go
  pkg/cmd/convert/edit/edit_test.go
  pkg/cmd/copy/copy.go
  pkg/cmd/copy/copy_test.go
  pkg/cmd/edit/edit.go
  pkg/cmd/edit/edit_test.go
  pkg/cmd/export/export_test.go
  pkg/cmd/import/import_test.go
  pkg/cmd/plugins/plugins.go
  pkg/cmd/plugins/upgrade/upgrade.go
  pkg/cmd/populate/populate.go
  pkg/cmd/populate/populate_test.go
  pkg/cmd/populate/templater.go
  pkg/cmd/populate/templater_test.go
  pkg/cmd/populate/templatertesting/run.go
  pkg/cmd/populate/templatertesting/types.go
  pkg/cmd/populate/test_data/template/secret-schema.yaml
  pkg/cmd/replicate/replicate.go
  pkg/cmd/replicate/replicate_test.go
  pkg/cmd/root.go
  pkg/cmd/vault/portforward/vault_portforward.go
  pkg/cmd/vault/portforward/vault_portforward_test.go
  pkg/cmd/vault/shell/shell.go
  pkg/cmd/vault/shell/shell_test.go
  pkg/cmd/vault/vault.go
  pkg/cmd/vault/wait/vault_wait.go
  pkg/cmd/vault/wait/vault_wait_test.go
  pkg/cmd/verify/verify.go
  pkg/cmd/wait/wait.go
  pkg/extsecrets/editor/factory/factory.go
  pkg/extsecrets/editor/local/local_editor.go
  pkg/extsecrets/editor/local/local_editor_test.go
  pkg/extsecrets/editor/vault/vault_editor.go
  pkg/extsecrets/file_client.go
  pkg/extsecrets/helpers_test.go
  pkg/extsecrets/secretfacade/load.go
  pkg/extsecrets/secretfacade/types.go
  pkg/extsecrets/secretfacade/verify_filter.go
  pkg/extsecrets/secretfacade/verify_filter_test.go
  pkg/masker/dump/main.go
  pkg/masker/masker.go
  pkg/masker/watcher/watcher.go
  pkg/schemas/helpers.go
  pkg/secretmapping/helpers.go
  pkg/vaults/vaultcli/helpers.go
Labels: approved, size/L

#320 fix: allow copy of secrets by name
  docs/cmd/jx-secret.md
  docs/cmd/jx-secret_convert.md
  docs/cmd/jx-secret_convert_edit.md
  docs/cmd/jx-secret_copy.md
  docs/cmd/jx-secret_edit.md
  docs/cmd/jx-secret_export.md
  docs/cmd/jx-secret_import.md
  docs/cmd/jx-secret_plugins.md
  docs/cmd/jx-secret_plugins_upgrade.md
  docs/cmd/jx-secret_populate.md
  docs/cmd/jx-secret_replicate.md
  docs/cmd/jx-secret_vault.md
  docs/cmd/jx-secret_vault_portforward.md
  docs/cmd/jx-secret_vault_shell.md
  docs/cmd/jx-secret_vault_wait.md
  docs/cmd/jx-secret_verify.md
  docs/cmd/jx-secret_version.md
  docs/cmd/jx-secret_wait.md
  docs/external.md
  docs/man/man1/jx-secret-copy.1
  docs/man/man1/jx-secret.1
  docs/mapping.md
  docs/schema.md
  pkg/cmd/copy/copy.go
  pkg/cmd/copy/copy_test.go
  pkg/cmd/root.go
Labels: approved, size/L

#321 fix: add debug logging CLI
  docs/cmd/jx-secret.md
  docs/cmd/jx-secret_convert.md
  docs/cmd/jx-secret_convert_edit.md
  docs/cmd/jx-secret_copy.md
  docs/cmd/jx-secret_edit.md
  docs/cmd/jx-secret_export.md
  docs/cmd/jx-secret_import.md
  docs/cmd/jx-secret_plugins.md
  docs/cmd/jx-secret_plugins_upgrade.md
  docs/cmd/jx-secret_populate.md
  docs/cmd/jx-secret_replicate.md
  docs/cmd/jx-secret_vault.md
  docs/cmd/jx-secret_vault_portforward.md
  docs/cmd/jx-secret_vault_shell.md
  docs/cmd/jx-secret_vault_wait.md
  docs/cmd/jx-secret_verify.md
  docs/cmd/jx-secret_version.md
  docs/cmd/jx-secret_wait.md
  docs/external.md
  docs/man/man1/jx-secret-convert.1
  docs/man/man1/jx-secret-populate.1
  docs/man/man1/jx-secret-replicate.1
  docs/man/man1/jx-secret-verify.1
  docs/mapping.md
  docs/schema.md
  go.mod
  go.sum
  pkg/cmd/convert/convert.go
  pkg/cmd/copy/copy.go
  pkg/cmd/replicate/replicate.go
  pkg/extsecrets/secretfacade/types.go
Labels: approved, size/L

#323 fix: issue not found or has no versions
  pkg/extsecrets/editor/gsm/gsm_editor.go
Labels: approved, size/XS

#324 chore: add better error reporting if we fail to parse GSM secret
  pkg/cmd/populate/populate_test.go
  pkg/cmd/populate/templater.go
  pkg/cmd/populate/test_data/load_requirements/jx-requirements.yml
  pkg/extsecrets/editor/gsm/gsm_editor.go
Labels: approved, size/M
