Repository jenkins-x-plugins/jx-secret, pull requests merged in 2021-07, with the labels that each got.

#343 fix: add better createValue method
  go.mod
  go.sum
  pkg/cmd/populate/populate.go
Labels: approved, size/L

#344 Feat/secret aws
  pkg/apis/external/v1/types.go
  pkg/apis/mapping/v1alpha1/types.go
  pkg/cmd/populate/populate.go
Labels: approved, lgtm, ok-to-test, size/XS

#345 fix: removed old secret editor code
  docs/cmd/jx-secret.md
  docs/cmd/jx-secret_convert.md
  docs/cmd/jx-secret_convert_edit.md
  docs/cmd/jx-secret_copy.md
  docs/cmd/jx-secret_edit.md
  docs/cmd/jx-secret_export.md
  docs/cmd/jx-secret_import.md
  docs/cmd/jx-secret_plugins.md
  docs/cmd/jx-secret_plugins_upgrade.md
  docs/cmd/jx-secret_populate.md
  docs/cmd/jx-secret_replicate.md
  docs/cmd/jx-secret_vault.md
  docs/cmd/jx-secret_vault_portforward.md
  docs/cmd/jx-secret_vault_shell.md
  docs/cmd/jx-secret_vault_wait.md
  docs/cmd/jx-secret_verify.md
  docs/cmd/jx-secret_version.md
  docs/cmd/jx-secret_wait.md
  docs/external.md
  docs/man/man1/jx-secret-export.1
  docs/man/man1/jx-secret-import.1
  docs/man/man1/jx-secret-vault-shell.1
  docs/man/man1/jx-secret.1
  docs/mapping.md
  docs/schema.md
  pkg/cmd/edit/edit.go
  pkg/cmd/edit/edit_test.go
  pkg/cmd/export/export.go
  pkg/cmd/export/export_test.go
  pkg/cmd/export/test_data/expected.yaml
  pkg/cmd/export/test_data/secrets/knative-docker-user-pass.yaml
  pkg/cmd/export/test_data/secrets/lighthouse-oauth-token.yaml
  pkg/cmd/import/import.go
  pkg/cmd/import/import_test.go
  pkg/cmd/import/test_data/import-file.yaml
  pkg/cmd/import/test_data/secrets/knative-docker-user-pass.yaml
  pkg/cmd/import/test_data/secrets/lighthouse-oauth-token.yaml
  pkg/cmd/populate/populate.go
  pkg/cmd/root.go
  pkg/cmd/vault/wait/vault_wait.go
  pkg/extsecrets/editor/azure/azure_editor.go
  pkg/extsecrets/editor/azure/azure_editor_test.go
  pkg/extsecrets/editor/factory/factory.go
  pkg/extsecrets/editor/gsm/gsm_editor.go
  pkg/extsecrets/editor/gsm/gsm_editor_test.go
  pkg/extsecrets/editor/gsm/test_data/write_multiline/expected.json
  pkg/extsecrets/editor/gsm/test_data/write_secrets/expected.json
  pkg/extsecrets/editor/gsm/test_data/write_single/expected.json
  pkg/extsecrets/editor/local/local_editor.go
  pkg/extsecrets/editor/local/local_editor_test.go
  pkg/extsecrets/editor/vault/vault_editor.go
  pkg/extsecrets/editor/vault/vault_editor_test.go
  pkg/extsecrets/secretfacade/load.go
  pkg/extsecrets/secretfacade/types.go
  pkg/vaults/vaultcli/masked_runner.go
  pkg/vaults/vaultcli/wait.go
  schema/kubernetes-client.io/v1/externalsecret.json
  schema/secret.jenkins-x.io/v1alpha1/secretmapping.json
Labels: approved, size/XXL

#346 fix: parse all secrets as k/v
  pkg/cmd/populate/populate.go
Labels: approved, lgtm, ok-to-test, size/XS

#348 chore: upgrade deps
  go.mod
  go.sum
Labels: approved, size/L

#352 fix: upgrade deps
  go.mod
  go.sum
  pkg/cmd/convert/convert_test.go
  pkg/cmd/convert/test_data/namespace-vault/.jx/secret/mapping/secret-mappings.yaml
  pkg/cmd/convert/test_data/namespace-vault/hmac/expected.yaml
  pkg/cmd/convert/test_data/namespace-vault/hmac/source.yaml
  pkg/cmd/convert/test_data/namespace-vault/oauth/expected.yaml
  pkg/cmd/convert/test_data/namespace-vault/oauth/source.yaml
  pkg/cmd/convert/test_data/namespace-vault/stringData/expected.yaml
  pkg/cmd/convert/test_data/namespace-vault/stringData/source.yaml
  pkg/schemas/generators/hmac_test.go
Labels: approved, size/L

#353 fix: avoid failing if folks create custom secret schemas
  pkg/schemas/helpers.go
Labels: approved, size/XS
