Repository jenkins-x-plugins/jx-secret, pull requests merged in 2021-01, with the labels that each got.

#188 chore: bump jx-api version
  go.mod
  go.sum
Labels: approved, lgtm, ok-to-test, size/XS

#191 chore: upgrade deps
  go.mod
  go.sum
Labels: approved, size/S

#195 chore: upgrade deps
  go.mod
  go.sum
  pkg/cmd/edit/edit_test.go
  pkg/cmd/export/export_test.go
  pkg/cmd/import/import_test.go
  pkg/cmd/populate/populate_test.go
  pkg/cmd/verify/verify_test.go
  pkg/cmd/wait/wait_test.go
  pkg/extsecrets/secretfacade/verify_filter_test.go
Labels: approved, lgtm, ok-to-test, size/L

#192 feat: added in ability for jx secret populate to optionally operate on ExternalSecrets within git rather than in cluster
  go.mod
  go.sum
  pkg/apis/external/v1/types.go
  pkg/cmd/edit/edit.go
  pkg/cmd/export/export.go
  pkg/cmd/import/import.go
  pkg/cmd/populate/populate.go
  pkg/cmd/populate/populate_test.go
  pkg/cmd/populate/test_data/filesystem/config-root/namespaces/jx/lighthouse-oauth-token.yaml
  pkg/cmd/verify/verify.go
  pkg/cmd/wait/wait.go
  pkg/extsecrets/client.go
  pkg/extsecrets/file_client.go
  pkg/extsecrets/interface.go
  pkg/extsecrets/secretfacade/load.go
  pkg/extsecrets/secretfacade/types.go
Labels: approved, lgtm, ok-to-test, size/L

#196 fix: update vault version from 1.4.2 to 1.6.1
  pkg/plugins/versions.go
Labels: approved, lgtm, ok-to-test, size/XS

#199 fix: upgrade deps
  go.mod
  go.sum
Labels: approved, size/S

#200 fix: upgrade deps
  go.mod
  go.sum
Labels: approved, size/XS

#203 chore: rolled back the k8s version
  go.mod
  go.sum
  pkg/cmd/edit/edit_test.go
  pkg/cmd/export/export_test.go
  pkg/cmd/import/import_test.go
  pkg/cmd/populate/populate_test.go
  pkg/cmd/verify/verify_test.go
  pkg/cmd/wait/wait_test.go
  pkg/extsecrets/secretfacade/verify_filter_test.go
  pkg/extsecrets/testsecrets/fake_client.go
Labels: approved, size/L

#210 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: size/M, updatebot

#211 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: size/S, updatebot

#212 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: updatebot

#219 chore: ugprade dependencies
  go.mod
  go.sum
  pkg/extsecrets/testsecrets/fake_client.go
Labels: approved, size/L

#214 feat: switched out external secrets editing for populate to new library
  go.mod
  go.sum
  pkg/cmd/populate/populate.go
  pkg/cmd/populate/populate_test.go
  pkg/extsecrets/editor/interface.go
  pkg/extsecrets/secretfacade/types.go
Labels: approved, lgtm, ok-to-test, size/L

#221 feat: fixed kube secret populate bug and add in more secret populate unit tests
  go.mod
  go.sum
  pkg/cmd/populate/populate.go
  pkg/cmd/populate/populate_test.go
  pkg/cmd/populate/test_data/azuresecrets/jenkins-maven-settings.yaml
  pkg/cmd/populate/test_data/azuresecrets/jenkins-x-bucketrepo.yaml
  pkg/cmd/populate/test_data/azuresecrets/jx-basic-auth-htpasswd.yaml
  pkg/cmd/populate/test_data/azuresecrets/knative-docker-user-pass.yaml
  pkg/cmd/populate/test_data/azuresecrets/lighthouse-hmac-token.yaml
  pkg/cmd/populate/test_data/azuresecrets/lighthouse-oauth-token.yaml
  pkg/cmd/populate/test_data/gsmsecrets/jenkins-maven-settings.yaml
  pkg/cmd/populate/test_data/gsmsecrets/jenkins-x-bucketrepo.yaml
  pkg/cmd/populate/test_data/gsmsecrets/jx-basic-auth-htpasswd.yaml
  pkg/cmd/populate/test_data/gsmsecrets/knative-docker-user-pass.yaml
  pkg/cmd/populate/test_data/gsmsecrets/lighthouse-hmac-token.yaml
  pkg/cmd/populate/test_data/gsmsecrets/lighthouse-oauth-token.yaml
  pkg/cmd/populate/test_data/kubesecrets/jenkins-maven-settings.yaml
  pkg/cmd/populate/test_data/kubesecrets/jenkins-x-bucketrepo.yaml
  pkg/cmd/populate/test_data/kubesecrets/jx-basic-auth-htpasswd.yaml
  pkg/cmd/populate/test_data/kubesecrets/knative-docker-user-pass.yaml
  pkg/cmd/populate/test_data/kubesecrets/lighthouse-hmac-token.yaml
  pkg/cmd/populate/test_data/kubesecrets/lighthouse-oauth-token.yaml
  pkg/cmd/populate/test_data/vaultsecrets/jenkins-maven-settings.yaml
  pkg/cmd/populate/test_data/vaultsecrets/jenkins-x-bucketrepo.yaml
  pkg/cmd/populate/test_data/vaultsecrets/jx-basic-auth-htpasswd.yaml
  pkg/cmd/populate/test_data/vaultsecrets/knative-docker-user-pass.yaml
  pkg/cmd/populate/test_data/vaultsecrets/lighthouse-hmac-token.yaml
  pkg/cmd/populate/test_data/vaultsecrets/lighthouse-oauth-token.yaml
Labels: approved, lgtm, ok-to-test, size/XL

#225 chore: dep bump
  go.mod
  go.sum
  pkg/cmd/populate/populate.go
  promote.sh
Labels: approved, lgtm, ok-to-test, size/S

#226 fix: added in vault auth configuration for jx secret populate
  pkg/cmd/populate/populate.go
  pkg/cmd/populate/populate_test.go
Labels: approved, ok-to-test, size/M

#229 fix: dep bump - fixed issue with vault secret paths being autoprefixed incorrectly.
  go.mod
  go.sum
Labels: approved, lgtm, ok-to-test, size/XS

#232 feat: added template functions to use secret facade library
  pkg/cmd/populate/populate_test.go
  pkg/cmd/populate/templater.go
  pkg/cmd/populate/templater_test.go
  pkg/cmd/populate/templatertesting/run.go
  pkg/cmd/populate/templatertesting/types.go
  pkg/cmd/populate/test_data/populate/azuresecrets/jenkins-maven-settings.yaml
  pkg/cmd/populate/test_data/populate/azuresecrets/jenkins-x-bucketrepo.yaml
  pkg/cmd/populate/test_data/populate/azuresecrets/jx-basic-auth-htpasswd.yaml
  pkg/cmd/populate/test_data/populate/azuresecrets/jx-requirements.yml
  pkg/cmd/populate/test_data/populate/azuresecrets/knative-docker-user-pass.yaml
  pkg/cmd/populate/test_data/populate/azuresecrets/lighthouse-hmac-token.yaml
  pkg/cmd/populate/test_data/populate/azuresecrets/lighthouse-oauth-token.yaml
  pkg/cmd/populate/test_data/populate/expected/jenkins-maven-settings/settings.xml/nexus.xml
  pkg/cmd/populate/test_data/populate/gsmsecrets/jenkins-maven-settings.yaml
  pkg/cmd/populate/test_data/populate/gsmsecrets/jenkins-x-bucketrepo.yaml
  pkg/cmd/populate/test_data/populate/gsmsecrets/jx-basic-auth-htpasswd.yaml
  pkg/cmd/populate/test_data/populate/gsmsecrets/jx-requirements.yml
  pkg/cmd/populate/test_data/populate/gsmsecrets/knative-docker-user-pass.yaml
  pkg/cmd/populate/test_data/populate/gsmsecrets/lighthouse-hmac-token.yaml
  pkg/cmd/populate/test_data/populate/gsmsecrets/lighthouse-oauth-token.yaml
  pkg/cmd/populate/test_data/populate/kubesecrets/jenkins-maven-settings.yaml
  pkg/cmd/populate/test_data/populate/kubesecrets/jenkins-x-bucketrepo.yaml
  pkg/cmd/populate/test_data/populate/kubesecrets/jx-basic-auth-htpasswd.yaml
  pkg/cmd/populate/test_data/populate/kubesecrets/jx-requirements.yml
  pkg/cmd/populate/test_data/populate/kubesecrets/knative-docker-user-pass.yaml
  pkg/cmd/populate/test_data/populate/kubesecrets/lighthouse-hmac-token.yaml
  pkg/cmd/populate/test_data/populate/kubesecrets/lighthouse-oauth-token.yaml
  pkg/cmd/populate/test_data/populate/secret-schema.yaml
  pkg/cmd/populate/test_data/populate/vaultsecrets/jenkins-maven-settings.yaml
  pkg/cmd/populate/test_data/populate/vaultsecrets/jenkins-x-bucketrepo.yaml
  pkg/cmd/populate/test_data/populate/vaultsecrets/jx-basic-auth-htpasswd.yaml
  pkg/cmd/populate/test_data/populate/vaultsecrets/jx-requirements.yml
  pkg/cmd/populate/test_data/populate/vaultsecrets/knative-docker-user-pass.yaml
  pkg/cmd/populate/test_data/populate/vaultsecrets/lighthouse-hmac-token.yaml
  pkg/cmd/populate/test_data/populate/vaultsecrets/lighthouse-oauth-token.yaml
  pkg/cmd/populate/test_data/populate_filesystem/config-root/namespaces/jx/lighthouse-oauth-token.yaml
  pkg/cmd/populate/test_data/template/expected/jenkins-docker-cfg-external/config.json/docker-gke.json
  pkg/cmd/populate/test_data/template/expected/jenkins-docker-cfg/config.json/docker-gke.json
  pkg/cmd/populate/test_data/template/expected/jenkins-maven-settings-external/settings.xml/bucketrepo.xml
  pkg/cmd/populate/test_data/template/expected/jenkins-maven-settings-external/settings.xml/nexus.xml
  pkg/cmd/populate/test_data/template/expected/jenkins-maven-settings-external/settings.xml/none.xml
  pkg/cmd/populate/test_data/template/expected/jenkins-maven-settings/settings.xml/bucketrepo.xml
  pkg/cmd/populate/test_data/template/expected/jenkins-maven-settings/settings.xml/nexus.xml
  pkg/cmd/populate/test_data/template/expected/jenkins-maven-settings/settings.xml/none.xml
  pkg/cmd/populate/test_data/template/expected/jx-basic-auth-htpasswd-external/auth/jx-basic-auth-htpasswd-external.txt
  pkg/cmd/populate/test_data/template/expected/jx-basic-auth-htpasswd/auth/jx-basic-auth-htpasswd.txt
  pkg/cmd/populate/test_data/template/secret-schema.yaml
Labels: approved, lgtm, ok-to-test, size/XXL

#234 fix: create some parity between k8s secret client and file secret client around namespaces
  go.mod
  go.sum
  pkg/extsecrets/file_client.go
Labels: approved, lgtm, ok-to-test, size/XS

#235 fix: upgrade pipelines and dependencies
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/release.yaml
  go.mod
  go.sum
Labels: approved, size/L

#236 fix: add udpatebot config
  .jx/updatebot.yaml
  promote.sh
Labels: approved, size/S

#238 fix: add fix for local secrets and annotations + type
  go.mod
  go.sum
  pkg/cmd/populate/populate.go
Labels: approved, size/S

#240 fix: local secret replication
  go.mod
  go.sum
  pkg/cmd/populate/populate.go
Labels: approved, size/S

#242 feat: allow setting of secret infra namespace on secret populate command
  pkg/cmd/populate/populate.go
  pkg/extsecrets/secretfacade/types.go
Labels: approved, lgtm, ok-to-test, size/XS

#241 chore: only verify gcloud is installed once rather than for every external secret
  pkg/cmd/edit/edit.go
  pkg/extsecrets/editor/gsm/gsm_editor.go
Labels: approved, size/S

#243 chore: upgrade pipelines
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: size/L, updatebot
