Repository jenkins-x-plugins/jx-secret, pull requests merged in 2021-05, with the labels that each got.

#325 fix: upgraded deps
  Makefile
  cmd/schemagen/main.go
  docs/cmd/jx-secret.md
  docs/cmd/jx-secret_convert.md
  docs/cmd/jx-secret_convert_edit.md
  docs/cmd/jx-secret_copy.md
  docs/cmd/jx-secret_edit.md
  docs/cmd/jx-secret_export.md
  docs/cmd/jx-secret_import.md
  docs/cmd/jx-secret_plugins.md
  docs/cmd/jx-secret_plugins_upgrade.md
  docs/cmd/jx-secret_populate.md
  docs/cmd/jx-secret_replicate.md
  docs/cmd/jx-secret_vault.md
  docs/cmd/jx-secret_vault_portforward.md
  docs/cmd/jx-secret_vault_shell.md
  docs/cmd/jx-secret_vault_wait.md
  docs/cmd/jx-secret_verify.md
  docs/cmd/jx-secret_version.md
  docs/cmd/jx-secret_wait.md
  docs/external.md
  docs/mapping.md
  docs/schema.md
  go.mod
  go.sum
  pkg/cmd/import/import_test.go
  pkg/extsecrets/editor/azure/azure_editor_test.go
  pkg/extsecrets/editor/gsm/gsm_editor_test.go
  pkg/extsecrets/secretfacade/verify_filter_test.go
  schema/kubernetes-client.io/v1/externalsecrets.json
  schema/secret.jenkins-x.io/v1alpha1/schemas.json
  schema/secret.jenkins-x.io/v1alpha1/secretmappings.json
Labels: approved, size/XL

#327 chore: add missing version property
  docs/external.md
  docs/mapping.md
  docs/schema.md
  pkg/apis/external/v1/types.go
  pkg/schematests/test_data/es.yaml
  pkg/schematests/validation_test.go
  schema/kubernetes-client.io/v1/externalsecret.json
Labels: approved, size/M

#328 fix: refactoring to support helm postrenderer
  Makefile
  go.mod
  go.sum
  pkg/cmd/convert/convert.go
  pkg/cmd/import/import_test.go
  pkg/cmd/populate/populate.go
  pkg/cmd/populate/populate_test.go
  pkg/schematests/validation_test.go
Labels: size/L

#329 chore: remove typo
  Makefile
Labels: approved, size/XS

#330 chore: ensure newlines (\n) from strings used when editing secrets
  pkg/cmd/edit/edit.go
  pkg/extsecrets/editor/gsm/gsm_editor_test.go
  pkg/extsecrets/editor/gsm/test_data/write_multiline/expected.json
Labels: approved, size/M

#331 chore: upgrade deps
  go.mod
  go.sum
Labels: approved, size/L

#332 fix: add optional to only copy secrets if the target namespace exists
  docs/cmd/jx-secret.md
  docs/cmd/jx-secret_convert.md
  docs/cmd/jx-secret_convert_edit.md
  docs/cmd/jx-secret_copy.md
  docs/cmd/jx-secret_edit.md
  docs/cmd/jx-secret_export.md
  docs/cmd/jx-secret_import.md
  docs/cmd/jx-secret_plugins.md
  docs/cmd/jx-secret_plugins_upgrade.md
  docs/cmd/jx-secret_populate.md
  docs/cmd/jx-secret_replicate.md
  docs/cmd/jx-secret_vault.md
  docs/cmd/jx-secret_vault_portforward.md
  docs/cmd/jx-secret_vault_shell.md
  docs/cmd/jx-secret_vault_wait.md
  docs/cmd/jx-secret_verify.md
  docs/cmd/jx-secret_version.md
  docs/cmd/jx-secret_wait.md
  docs/external.md
  docs/man/man1/jx-secret-copy.1
  docs/mapping.md
  docs/schema.md
  pkg/cmd/copy/copy.go
  schema/kubernetes-client.io/v1/externalsecret.json
  schema/secret.jenkins-x.io/v1alpha1/schema.json
  schema/secret.jenkins-x.io/v1alpha1/secretmapping.json
Labels: approved, size/L
